# Generated by Django 4.1.7 on 2023-04-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=32),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='email',
            field=models.CharField(default='email', max_length=32),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='nroCelular',
            field=models.CharField(default='987654321', max_length=32),
        ),
    ]
